apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 5.8.1
    chart: prometheus-blackbox-exporter
    helm: 
      parameters:
        - name: serviceMonitor.targets[0]
          value: | 
            - name: nginx
              url: http://nginx.web:8080
        - name: serviceMonitor.enabled
          value: 'true'
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
