apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://grafana.github.io/loki/charts'
    targetRevision: 2.1.2
    chart: loki-stack
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true